config/routes.rb
Rails.application.routes.draw do
  root 'presentations#index'

  get 'static_pages/about'

  get 'static_pages/contact'

  resources :presentations do
    resources :comments
  end

  resources :tags, only: [:show]
  resources :categories, only: [:show, :index]  
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :presentations
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id              :integer          not null, primary key
#  author_name     :string
#  body            :text
#  presentation_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :presentation
end

app/models/presentation.rb
# == Schema Information
#
# Table name: presentations
#
#  id                :integer          not null, primary key
#  title             :string
#  body              :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  presentation_file :string
#  category_id       :integer
#

class Presentation < ActiveRecord::Base
  mount_uploader :presentation_file, CwpresentationUploader
  has_many :comments
  belongs_to :category
  has_many :taggings
  has_many :tags, through: :taggings

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(', ')
  end

  def tag_list=(tags_string)
    # Split the tags_string into an array of strings with leading and trailing
    # whitespace removed (so "tag1, tag2, tag3" would become ["tag1","tag2","tag3"])
    # For each of those strings… ensure each one of these strings are unique
    # Look for a Tag object with that name. If there isn’t one, create it.
    # Add the tag object to a list of tags for the article
    # Set the article’s tags to the list of tags that we have found and/or created.

    tag_names = tags_string.split(', ').collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect{|name| Tag.find_or_create_by(name: name)}
    self.tags = new_or_found_tags
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :presentations, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :presentation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :categories_on_head

  def categories_on_head
    @categories_on_head = Category.all[0..3]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @presentations = @category.presentations
  end

  def index
    @categories = Category.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(params_comment)
    comment.presentation_id = params[:presentation_id]
    if comment.save
      flash[:success] = "Success! your comment has been posted"
      redirect_to presentation_url(comment.presentation.id)
    else
      flash[:failure] = "Your comment could not be posted"
      redirect_to presentation_url(comment.presentation.id)
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.delete
    redirect_to presentation_path(params[:presentation_id])
  end

  private
    def params_comment
      params.require(:comment).permit(:author_name, :body)
    end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  include PresentationsHelper
  def index
    @presentations = Presentation.all
  end

  def show
    @presentation = Presentation.find(params[:id])
    # only for production
    @presentation_link =  Rack::Utils.escape(@presentation.presentation_file.url)
    @presentation_link = "http://docs.google.com/viewer?url=" + @presentation_link
    @comment = Comment.new
    @comment.presentation_id = @presentation.id
  end

  def new
    @presentation = Presentation.new
    @categories = Category.all
  end

  def create
    presentation = Presentation.new(params_presentation)
    if(presentation.save)
      flash[:success] = "Congratulations! Presentation Saved!"
      redirect_to presentation_path(presentation)
    else
      flash.now = "Presentation Save Failed!"
      render action: 'new'
    end
  end

  def destroy
    presentation = Presentation.find(params[:id])
    if presentation.destroy
      redirect_to presentations_path
    else
      render presentation_path(presentation)
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag =  Tag.find(params[:id])
    @presentations = @tag.presentations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
  def params_presentation
    params.require(:presentation).permit(:title, :body, :presentation_file, :category_id, :tag_list)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/categories/index.html.erb
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<ul>
  <% @presentations.each do |presentation| %>
    <%= link_to presentation.title, presentation_url(presentation) %>
  <% end %>
</ul>

app/views/comments/_form.html.erb
<div class="row" style="margin-bottom: 2vh;">
  <%= form_for([@presentation, @comment]) do |f| %>
  <div class="col-md-12">
    <!-- input for title -->
    <div class="form-group">
      <div class="input-group">
          <%= f.text_field :author_name, class: 'form-control', placeholder: 'Your Name' %>
          <span class="input-group-addon"></span>
      </div>
    </div>

    <!-- input for description -->
    <div class="form-group">
      <div class="input-group">
        <%= f.text_area :body, class: 'form-control', rows: 3, placeholder: 'Your Message' %>
        <span class="input-group-addon"></span>
      </div>
    </div>


    <!-- submit -->
    <%= f.submit "Comment", class: "btn btn-default pull-right" %>
  </div><!-- / col-md-6 col-md-offset-3 -->
  <% end %>
</div><!-- END row -->

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container-fluid" id="common-footer"></div>
</div>

app/views/layouts/_ganalytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58586341-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" id="navbar-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_url %>"><span id="slide">Slide</span><span id="share">Square</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group has-feedback">
          <input type="text" class="form-control form-nav" placeholder="Search">
          <i class="fa fa-search form-control-feedback"></i>
        </div>
        <button type="submit" class="btn btn-default form-nav-button">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= new_presentation_url %>">Upload <%= icon('fa fa-cloud-upload') %></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= icon('fa fa-user') %></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Profile</a></li>
            <li><a href="#"></a></li>
            <li class="divider"></li>
            <li><a href="#">Log Out</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<nav class="navbar navbar-default" id="category-bar">
    <div class="container">
        <ul class="nav navbar-nav nav-justified">
          <li><%= link_to "Home", root_url %></li>
          <% @categories_on_head.each do |category| %>
            <li><%= link_to category.name, category_path(category) %></li>
          <% end %>
          <li><%= link_to "More Topics", categories_url %></li>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SlideSquare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render partial: 'layouts/ganalytics' %>
</head>
  <body>
    <%= render partial: 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
    <%= render partial: 'layouts/footer' %>
</html>

app/views/presentations/_comment.html.erb
<div class="well">
  <%= link_to icon('fa fa-trash-o'), presentation_comment_path(@presentation,comment), method: :delete, class: 'pull-right' %>
  <h4>Comment by <%= comment.author_name %></h4>
  <p><%= comment.body %></p>
  <p class="created-at-text">Created <%= time_ago_in_words(comment.created_at) %> ago</p>
</div>

app/views/presentations/_tag.html.erb
<span class="dull-text .tag"><%= link_to tag.name, tag_path(tag) %>&nbsp;</span>

app/views/presentations/index.html.erb
<h2>Presentations</h2>

<% @presentations.each do |presentation| %>
<div class="col-xs-12 col-sm-4 col-md-4">
  <div class="thumbnail">
    <%= link_to image_tag("image.svg", size: '350x350'), presentation_path(presentation) %>
    <div class="caption">
      <p></p>
      <h5><%= link_to truncate(presentation.title), presentation_path(presentation) %></h5>
      <p><a href="#" class="fa fa-heart pull-right"></a> <a href="#" class="fa fa-download pull-right"></a> <a href="#" class="fa fa-share pull-right" ></a></p>
    </div>
  </div>
</div>
<% end %>

app/views/presentations/new.html.erb
<div class="row">
  <%= form_for(@presentation, html: { multipart: true }) do |f| %>
  <div class="col-md-6 col-md-offset-3">
    <h2>New Presentation</h2><br />
    <!-- input for title -->
    <div class="form-group">
      <div class="input-group">
          <%= f.text_field :title, class: 'form-control', placeholder: 'Presentation Title' %>
          <span class="input-group-addon"></span>
      </div>
    </div>

    <!-- input for description -->
    <div class="form-group">
      <div class="input-group">
        <%= f.text_area :body, class: 'form-control', rows: 5, placeholder: 'Presentation Description' %>
        <span class="input-group-addon"></span>
      </div>
    </div>

    <!-- input for tags -->
    <div class="form-group">
      <div class="input-group">
        <%= f.text_field :tag_list, class: 'form-control', placeholder: 'Please enter the tags separated by a comma' %>
        <span class="input-group-addon"></span>
      </div>
    </div>

    <div class="form-group">
      <div class="input-group">
        <%= f.file_field :presentation_file, class: 'form-control' %>
        <span class="input-group-addon"></span>
      </div>
    </div>

    <div class="form-group">
      <div class="input-group">
        <%= f.select("category_id", options_for_select(@categories.collect{|category| [category.name, category.id]})) %>
      </div>
    </div>

    <!-- submit -->
    <%= f.submit "Create Presentation", class: "btn btn-default pull-right" %>
  </div><!-- / col-md-6 col-md-offset-3 -->
  <% end %>
</div><!-- END row -->

app/views/presentations/show.html.erb
<div class="col-md-9">
  <div class="col-md-12">
    <h2><%= @presentation.title %></h2>
    <h5 class="dull-text"><%= @presentation.category.name %></h5>
    <%= link_to "All Presentations", presentations_path, class: 'btn btn-default' %>
    <%= link_to "Delete", presentation_path(@presentation), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-default' %>
    <p><%= @presentation.body %></p>
    <iframe src="<%= @presentation_link %>&embedded=true" width="600" height="780" style="border: none;"></iframe>
  </div>
  <div class="col-md-12">
    <%= render partial: 'tag', collection: @presentation.tags %>
    <h3><b>What's on your mind?</b></h3>
    <%= render partial: 'comments/form' %>
    <% if @presentation.comments.count<1 %>
      <p>No comments</p>
    <% else %>
      <%= render partial: 'comment', collection: @presentation.comments %>
    <% end %>
  </div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("image.svg", size: '350x350') %>
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="fa fa-heart pull-right"></a> <a href="#" class="fa fa-download pull-right"></a> <a href="#" class="fa fa-share pull-right" ></a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("image.svg", size: '350x350') %>
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="fa fa-heart pull-right"></a> <a href="#" class="fa fa-download pull-right"></a> <a href="#" class="fa fa-share pull-right" ></a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("image.svg", size: '350x350') %>
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="fa fa-heart pull-right"></a> <a href="#" class="fa fa-download pull-right"></a> <a href="#" class="fa fa-share pull-right" ></a></p>
      </div>
    </div>
  </div>
</div>

<hr />

<div class="row">
  <div class="col-xs-12 col-sm-3 col-md-3">
    <div class="thumbnail">
      <%= image_tag("image.svg", size: '350x350') %>
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="fa fa-heart pull-right"></a> <a href="#" class="fa fa-download pull-right"></a> <a href="#" class="fa fa-share pull-right" ></a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-3 col-md-3">
    <div class="thumbnail">
      <%= image_tag("image.svg", size: '350x350') %>
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="fa fa-heart pull-right"></a> <a href="#" class="fa fa-download pull-right"></a> <a href="#" class="fa fa-share pull-right" ></a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-3 col-md-3">
    <div class="thumbnail">
      <%= image_tag("image.svg", size: '350x350') %>
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="fa fa-heart pull-right"></a> <a href="#" class="fa fa-download pull-right"></a> <a href="#" class="fa fa-share pull-right" ></a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-3 col-md-3">
    <div class="thumbnail">
      <%= image_tag("image.svg", size: '350x350') %>
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="fa fa-heart pull-right"></a> <a href="#" class="fa fa-download pull-right"></a> <a href="#" class="fa fa-share pull-right" ></a></p>
      </div>
    </div>
  </div>

</div>

<hr />

<div class="row">
  <div class="col-xs-12 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("image.svg", size: '350x350') %>
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="fa fa-heart pull-right"></a> <a href="#" class="fa fa-download pull-right"></a> <a href="#" class="fa fa-share pull-right" ></a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("image.svg", size: '350x350') %>
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="fa fa-heart pull-right"></a> <a href="#" class="fa fa-download pull-right"></a> <a href="#" class="fa fa-share pull-right" ></a></p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag("image.svg", size: '350x350') %>
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="fa fa-heart pull-right"></a> <a href="#" class="fa fa-download pull-right"></a> <a href="#" class="fa fa-share pull-right" ></a></p>
      </div>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<div class="col-md-9">
  <h2><%= @tag.name %></h2>
  <div class="col-md-12">
    <% @presentations.each do |presentation| %>
      <h5><%= link_to presentation.title, presentation_path(presentation) %></h5>
    <% end %>
  </div>
</div>